version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    hostname: zookeeper
    networks:
      - event-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc -q 1 localhost 2181 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s


  kafka:
    image: bitnami/kafka:3.4
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - event-network
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL",
              "kafka-topics.sh --bootstrap-server localhost:9092 --list &&
               kafka-broker-api-versions.sh --bootstrap-server localhost:9092"
      ]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s  # Increased startup time

networks:
  event-network:
    driver: bridge